/**
 * Produces the comparison table in README.md. See MEASUREMENT.md for the
 * definitions of every metric. Run with: bun scripts/measure.ts
 */
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs'
import { join, relative, basename } from 'node:path'
import { spawnSync } from 'node:child_process'
import { getEncoding } from 'js-tiktoken'

const IMPLEMENTATIONS = ['guren', 'hono', 'nextjs', 'tanstack', 'adonisjs', 'nestjs'] as const

const EXCLUDED_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  'dist',
  'build',
  'out',
  '.guren', // Guren codegen output
  '.output', // TanStack Start / Nitro build output
  '.tanstack',
  '.nitro',
  '.vinxi',
  '.adonisjs',
  '.vercel',
  'coverage',
])
// Note: drizzle-kit migration dirs need no entry here — their .sql/.json files
// are already outside COUNTED_EXTENSIONS. Hand-written migration classes
// (e.g. AdonisJS database/migrations/*.ts) are code and DO count.

const EXCLUDED_FILES = new Set([
  'next-env.d.ts', // generated by Next.js
  'bun.lock',
  'bun.lockb',
  'package-lock.json',
])

const COUNTED_EXTENSIONS = ['.ts', '.tsx', '.css']

type FileKind = 'source' | 'config' | 'test'

interface Metrics {
  sourceFiles: number
  sourceLoc: number
  configLoc: number
  testFiles: number
  testLoc: number
  directDeps: number
  contextTokens: number
  handwrittenLoc: number
}

const encoder = getEncoding('cl100k_base')

function isConfig(path: string): boolean {
  const name = basename(path)
  return (
    /\.config\.(ts|js|mjs|cjs)$/.test(name) ||
    /^tsconfig.*\.json$/.test(name) ||
    name === '.env.example'
  )
}

function isTest(path: string): boolean {
  return (
    /\.(test|spec)\.tsx?$/.test(path) ||
    path.split('/').some((seg) => seg === 'tests' || seg === '__tests__' || seg === 'e2e')
  )
}

function classify(path: string): FileKind {
  if (isTest(path)) return 'test'
  if (isConfig(path)) return 'config'
  return 'source'
}

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (!EXCLUDED_DIRS.has(entry)) yield* walk(full)
      continue
    }
    if (EXCLUDED_FILES.has(entry)) continue
    if (COUNTED_EXTENSIONS.some((ext) => entry.endsWith(ext)) || isConfig(full)) {
      yield full
    }
  }
}

function nonBlankLines(content: string): number {
  return content.split('\n').filter((line) => line.trim().length > 0).length
}

/**
 * Lines the developer actually wrote: non-blank lines added relative to the
 * pristine generator output committed under baselines/<impl>. With no
 * baseline (hono has no scaffold), every line is handwritten.
 */
function handwrittenLines(baselineDir: string | null, file: string, root: string): number {
  const content = readFileSync(file, 'utf8')
  const baselineFile = baselineDir ? join(baselineDir, relative(root, file)) : null

  if (!baselineFile || !existsSync(baselineFile)) {
    return nonBlankLines(content)
  }

  const diff = spawnSync('git', ['diff', '--no-index', '--', baselineFile, file], { encoding: 'utf8' })
  return diff.stdout
    .split('\n')
    .filter((line) => line.startsWith('+') && !line.startsWith('+++') && line.slice(1).trim().length > 0)
    .length
}

function measure(root: string, baselineDir: string | null): Metrics {
  const metrics: Metrics = {
    sourceFiles: 0,
    sourceLoc: 0,
    configLoc: 0,
    testFiles: 0,
    testLoc: 0,
    directDeps: 0,
    contextTokens: 0,
    handwrittenLoc: 0,
  }

  for (const file of walk(root)) {
    const content = readFileSync(file, 'utf8')
    const loc = nonBlankLines(content)
    const kind = classify(relative(root, file))

    if (kind === 'test') {
      metrics.testFiles += 1
      metrics.testLoc += loc
    } else if (kind === 'config') {
      metrics.configLoc += loc
      metrics.contextTokens += encoder.encode(content).length
      metrics.handwrittenLoc += handwrittenLines(baselineDir, file, root)
    } else {
      metrics.sourceFiles += 1
      metrics.sourceLoc += loc
      metrics.contextTokens += encoder.encode(content).length
      metrics.handwrittenLoc += handwrittenLines(baselineDir, file, root)
    }
  }

  const pkgPath = join(root, 'package.json')
  if (existsSync(pkgPath)) {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    metrics.directDeps =
      Object.keys(pkg.dependencies ?? {}).length + Object.keys(pkg.devDependencies ?? {}).length
  }

  return metrics
}

const repoRoot = join(import.meta.dirname, '..')
const rows: string[] = []

rows.push('| Metric | ' + IMPLEMENTATIONS.map((impl) => `\`${impl}/\``).join(' | ') + ' |')
rows.push('|--------|' + IMPLEMENTATIONS.map(() => '------').join('|') + '|')

const results = IMPLEMENTATIONS.map((impl) => {
  const dir = join(repoRoot, impl)
  const baselineDir = join(repoRoot, 'baselines', impl)
  return existsSync(dir) ? measure(dir, existsSync(baselineDir) ? baselineDir : null) : null
})

function row(label: string, pick: (metric: Metrics) => number): string {
  const cells = results.map((result) => (result ? pick(result).toLocaleString('en-US') : '—'))
  return `| ${label} | ${cells.join(' | ')} |`
}

rows.push(row('Source files', (metric) => metric.sourceFiles))
rows.push(row('Source LOC', (metric) => metric.sourceLoc))
rows.push(row('Handwritten LOC (vs scaffold)', (metric) => metric.handwrittenLoc))
rows.push(row('Config LOC', (metric) => metric.configLoc))
rows.push(row('Test files', (metric) => metric.testFiles))
rows.push(row('Test LOC', (metric) => metric.testLoc))
rows.push(row('Direct dependencies', (metric) => metric.directDeps))
rows.push(row('Context tokens (cl100k)', (metric) => metric.contextTokens))

console.log(rows.join('\n'))
