/**
 * Produces the comparison table in README.md. See MEASUREMENT.md for the
 * definitions of every metric. Run with: bun scripts/measure.ts
 */
import { readdirSync, readFileSync, statSync, existsSync, writeFileSync } from 'node:fs'
import { join, relative, basename } from 'node:path'
import { spawnSync } from 'node:child_process'
import { getEncoding } from 'js-tiktoken'

const IMPLEMENTATIONS = ['guren', 'hono', 'nextjs', 'tanstack', 'adonisjs', 'nestjs'] as const

const EXCLUDED_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  'dist',
  'build',
  'out',
  '.guren', // Guren codegen output
  '.wasp', // Wasp compiler output (.wasp/out)
  '.output', // TanStack Start / Nitro build output
  '.tanstack',
  '.nitro',
  '.vinxi',
  '.adonisjs',
  '.vercel',
  'coverage',
])
// Note: drizzle-kit migration dirs need no entry here — their .sql/.json files
// are already outside COUNTED_EXTENSIONS. Hand-written migration classes
// (e.g. AdonisJS database/migrations/*.ts) are code and DO count.

const EXCLUDED_FILES = new Set([
  'next-env.d.ts', // generated by Next.js
  'bun.lock',
  'bun.lockb',
  'package-lock.json',
])

// Generated files identified by path relative to the implementation root —
// for cases where a basename rule would also hit hand-written files elsewhere.
const EXCLUDED_RELATIVE_PATHS = new Set([
  'database/schema.ts', // AdonisJS: regenerated by `node ace migration:run`
  'types/generated/routes.d.ts', // Guren: "DO NOT EDIT" output of `guren codegen`
])

// Committed Vite build output. Its .js siblings fall outside COUNTED_EXTENSIONS
// already; counting the one hashed .css beside them was an accident of the
// extension list, not a rule.
const EXCLUDED_DIR_PREFIXES = ['public/assets/']

// .prisma: author-written data-model definitions count regardless of extension,
// same as Drizzle/Lucid schemas in .ts. See MEASUREMENT.md.
const COUNTED_EXTENSIONS = ['.ts', '.tsx', '.css', '.prisma']

/**
 * Agent-harness guidance: the files a coding agent's harness loads as
 * instructions rather than as application code. They are prose and settings, so
 * no code metric can see them, yet they are exactly what an agent reads before
 * touching the project — which makes leaving them uncounted the one omission
 * most likely to flatter whichever implementation ships the most of them.
 *
 * Reported in their own rows, never folded into Source LOC or Context tokens:
 * those measure the cost of reading the app, and mixing guidance in would
 * destroy that meaning. Files here that ARE counted code (guren's hook is a
 * .ts file) are left to the code metrics so nothing is counted twice.
 */
const AGENT_GUIDANCE_PATHS = [
  'CLAUDE.md',
  'AGENTS.md',
  '.cursorrules',
  '.claude/',
  '.cursor/',
  '.agents/',
  '.github/instructions/',
]

function isAgentGuidance(relPath: string): boolean {
  if (COUNTED_EXTENSIONS.some((ext) => relPath.endsWith(ext))) return false
  return AGENT_GUIDANCE_PATHS.some(
    (entry) => relPath === entry || relPath.startsWith(entry),
  )
}

type FileKind = 'source' | 'config' | 'test' | 'verification'

interface Metrics {
  sourceFiles: number
  sourceLoc: number
  configLoc: number
  testFiles: number
  testLoc: number
  directDeps: number
  contextTokens: number
  handwrittenLoc: number
  verificationFiles: number
  verificationLoc: number
  guidanceFiles: number
  guidanceLoc: number
  guidanceTokens: number
}

const encoder = getEncoding('cl100k_base')

function isConfig(path: string): boolean {
  const name = basename(path)
  return (
    /\.config\.(ts|js|mjs|cjs)$/.test(name) ||
    /^tsconfig.*\.json$/.test(name) ||
    name === '.env.example'
  )
}

function isTest(path: string): boolean {
  return (
    /[.-](test|spec)\.tsx?$/.test(path) || // .test.ts / .spec.ts / e2e-spec.ts
    path.split('/').some((seg) => seg === 'test' || seg === 'tests' || seg === '__tests__' || seg === 'e2e')
  )
}

function classify(path: string): FileKind {
  // Spec-compliance tests written by this repository for a framework that
  // documents no support for the layer SPEC §6 tests. Reported on its own row
  // rather than dropped: the code exists and someone had to write it.
  if (path === 'verification' || path.startsWith('verification/')) return 'verification'
  if (isTest(path)) return 'test'
  if (isConfig(path)) return 'config'
  return 'source'
}

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (!EXCLUDED_DIRS.has(entry)) yield* walk(full)
      continue
    }
    if (EXCLUDED_FILES.has(entry)) continue
    if (/\.gen\.tsx?$/.test(entry)) continue // codegen output by convention (e.g. routeTree.gen.ts)
    if (COUNTED_EXTENSIONS.some((ext) => entry.endsWith(ext)) || isConfig(full)) {
      yield full
    }
  }
}

/** Like walk(), but extension-agnostic — agent guidance is .md and .json. */
function* walkAll(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (entry !== 'node_modules' && entry !== '.git') yield* walkAll(full)
      continue
    }
    yield full
  }
}

function nonBlankLines(content: string): number {
  return content.split('\n').filter((line) => line.trim().length > 0).length
}

/**
 * Lines the developer actually wrote: non-blank lines added relative to the
 * pristine generator output committed under baselines/<impl>. With no
 * baseline (hono has no scaffold), every line is handwritten.
 */
function handwrittenLines(baselineDir: string | null, file: string, root: string): number {
  const content = readFileSync(file, 'utf8')
  const baselineFile = baselineDir ? join(baselineDir, relative(root, file)) : null

  if (!baselineFile || !existsSync(baselineFile)) {
    return nonBlankLines(content)
  }

  const diff = spawnSync('git', ['diff', '--no-index', '--', baselineFile, file], { encoding: 'utf8' })
  return diff.stdout
    .split('\n')
    .filter((line) => line.startsWith('+') && !line.startsWith('+++') && line.slice(1).trim().length > 0)
    .length
}

/**
 * Per-area LOC, for the "Where the lines go" table in README.md.
 *
 * The rules below were recovered from the tree at 75be922 (the commit that
 * first published that table by hand) and reproduce every row of it except
 * Plumbing, which was computed inconsistently there: config files were folded
 * into it for `nextjs/` but not for the others, and the guren/hono figures were
 * 2 and 4 lines low. Config LOC has its own column in the main table, so areas
 * cover Source files only, and two checks keep them honest: a source file that
 * matches no rule is a hard error (so a new file has to be classified, not
 * silently absorbed), and the area totals must sum to Source LOC. There is
 * deliberately no catch-all rule — one would make the first check unreachable.
 *
 * First matching prefix wins, so order matters (nextjs' auth route handler
 * lives under src/app/ and must be claimed before the Frontend rule).
 */
const AREAS = [
  'Frontend (React UI)',
  'Routes / controllers / actions',
  'DB + models',
  'Auth',
  'Validation + serialization + authz',
  'Plumbing (bootstrap / providers)',
  'Agent harness (hook)',
] as const

type Area = (typeof AREAS)[number]

const AREA_RULES: Record<string, Array<[string, Area]>> = {
  guren: [
    ['.claude/', 'Agent harness (hook)'],
    ['resources/', 'Frontend (React UI)'],
    ['public/', 'Frontend (React UI)'],
    ['app/Http/Controllers/', 'Routes / controllers / actions'],
    ['routes/', 'Routes / controllers / actions'],
    ['app/Models/', 'DB + models'],
    ['db/', 'DB + models'],
    ['app/Http/Validators/', 'Validation + serialization + authz'],
    ['app/Http/Resources/', 'Validation + serialization + authz'],
    ['app/Policies/', 'Validation + serialization + authz'],
    ['app/Providers/', 'Plumbing (bootstrap / providers)'],
    ['app/Jobs/', 'Plumbing (bootstrap / providers)'],
    ['bin/', 'Plumbing (bootstrap / providers)'],
    ['config/', 'Plumbing (bootstrap / providers)'],
    ['src/', 'Plumbing (bootstrap / providers)'],
  ],
  hono: [
    ['src/client/', 'Frontend (React UI)'],
    ['src/server/routes/', 'Routes / controllers / actions'],
    ['src/server/db/', 'DB + models'],
    ['src/server/auth/', 'Auth'],
    ['src/server/validation.ts', 'Validation + serialization + authz'],
    ['src/server/', 'Plumbing (bootstrap / providers)'],
  ],
  nextjs: [
    ['src/app/api/auth/', 'Auth'],
    ['src/auth.ts', 'Auth'],
    ['src/app/', 'Frontend (React UI)'],
    ['src/lib/actions/', 'Routes / controllers / actions'],
    ['src/db/', 'DB + models'],
    ['src/lib/data.ts', 'DB + models'],
    ['src/lib/validation.ts', 'Validation + serialization + authz'],
    ['src/proxy.ts', 'Plumbing (bootstrap / providers)'],
  ],
}

const AREA_IMPLEMENTATIONS = Object.keys(AREA_RULES)

function areaFor(impl: string, relPath: string): Area | null {
  for (const [prefix, area] of AREA_RULES[impl]) {
    if (relPath.startsWith(prefix)) return area
  }
  return null
}

function measureAreas(root: string, impl: string): Map<Area, number> {
  const totals = new Map<Area, number>(AREAS.map((area) => [area, 0]))

  for (const file of walk(root)) {
    const rel = relative(root, file)
    if (EXCLUDED_RELATIVE_PATHS.has(rel)) continue
    if (EXCLUDED_DIR_PREFIXES.some((prefix) => rel.startsWith(prefix))) continue
    if (classify(rel) !== 'source') continue

    const area = areaFor(impl, rel)
    if (!area) {
      throw new Error(`${impl}: no area rule matches ${rel} — add one to AREA_RULES`)
    }
    totals.set(area, totals.get(area)! + nonBlankLines(readFileSync(file, 'utf8')))
  }

  return totals
}

function measure(root: string, baselineDir: string | null): Metrics {
  const metrics: Metrics = {
    sourceFiles: 0,
    sourceLoc: 0,
    configLoc: 0,
    testFiles: 0,
    testLoc: 0,
    directDeps: 0,
    contextTokens: 0,
    handwrittenLoc: 0,
    verificationFiles: 0,
    verificationLoc: 0,
    guidanceFiles: 0,
    guidanceLoc: 0,
    guidanceTokens: 0,
  }

  for (const file of walk(root)) {
    const relPath = relative(root, file)
    if (EXCLUDED_RELATIVE_PATHS.has(relPath)) {
      continue
    }
    if (EXCLUDED_DIR_PREFIXES.some((prefix) => relPath.startsWith(prefix))) {
      continue
    }
    const content = readFileSync(file, 'utf8')
    const loc = nonBlankLines(content)
    const kind = classify(relPath)

    if (kind === 'verification') {
      metrics.verificationFiles += 1
      metrics.verificationLoc += loc
    } else if (kind === 'test') {
      metrics.testFiles += 1
      metrics.testLoc += loc
    } else if (kind === 'config') {
      metrics.configLoc += loc
      metrics.contextTokens += encoder.encode(content).length
      metrics.handwrittenLoc += handwrittenLines(baselineDir, file, root)
    } else {
      metrics.sourceFiles += 1
      metrics.sourceLoc += loc
      metrics.contextTokens += encoder.encode(content).length
      metrics.handwrittenLoc += handwrittenLines(baselineDir, file, root)
    }
  }

  for (const file of walkAll(root)) {
    const relPath = relative(root, file)
    if (!isAgentGuidance(relPath)) continue
    const content = readFileSync(file, 'utf8')
    metrics.guidanceFiles += 1
    metrics.guidanceLoc += nonBlankLines(content)
    metrics.guidanceTokens += encoder.encode(content).length
  }

  const pkgPath = join(root, 'package.json')
  if (existsSync(pkgPath)) {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    metrics.directDeps =
      Object.keys(pkg.dependencies ?? {}).length + Object.keys(pkg.devDependencies ?? {}).length
  }

  return metrics
}

const repoRoot = join(import.meta.dirname, '..')
const rows: string[] = []

rows.push('| Metric | ' + IMPLEMENTATIONS.map((impl) => `\`${impl}/\``).join(' | ') + ' |')
rows.push('|--------|' + IMPLEMENTATIONS.map(() => '------').join('|') + '|')

const results = IMPLEMENTATIONS.map((impl) => {
  const dir = join(repoRoot, impl)
  const baselineDir = join(repoRoot, 'baselines', impl)
  return existsSync(dir) ? measure(dir, existsSync(baselineDir) ? baselineDir : null) : null
})

function row(label: string, pick: (metric: Metrics) => number): string {
  const cells = results.map((result) => (result ? pick(result).toLocaleString('en-US') : '—'))
  return `| ${label} | ${cells.join(' | ')} |`
}

rows.push(row('Source files', (metric) => metric.sourceFiles))
rows.push(row('Source LOC', (metric) => metric.sourceLoc))
rows.push(row('Handwritten LOC (vs scaffold)', (metric) => metric.handwrittenLoc))
rows.push(row('Config LOC', (metric) => metric.configLoc))
rows.push(row('Test files', (metric) => metric.testFiles))
rows.push(row('Test LOC', (metric) => metric.testLoc))
rows.push(row('Direct dependencies', (metric) => metric.directDeps))
rows.push(row('Context tokens (cl100k)', (metric) => metric.contextTokens))
rows.push(row('External verification LOC', (metric) => metric.verificationLoc))
rows.push(row('Agent guidance LOC', (metric) => metric.guidanceLoc))
rows.push(row('Agent guidance tokens (cl100k)', (metric) => metric.guidanceTokens))

const table = rows.join('\n')

const areaRows: string[] = []
areaRows.push('| Area | ' + AREA_IMPLEMENTATIONS.map((impl) => `\`${impl}/\``).join(' | ') + ' |')
areaRows.push('|------|' + AREA_IMPLEMENTATIONS.map(() => '---------:').join('|') + '|')

const areaTotals = AREA_IMPLEMENTATIONS.map((impl) => measureAreas(join(repoRoot, impl), impl))

// Reconciliation: areas cover exactly the Source files, so they must sum to
// Source LOC. This is what the hand-built table got wrong.
AREA_IMPLEMENTATIONS.forEach((impl, index) => {
  const sum = [...areaTotals[index].values()].reduce((a, b) => a + b, 0)
  const expected = results[IMPLEMENTATIONS.indexOf(impl as (typeof IMPLEMENTATIONS)[number])]?.sourceLoc
  if (sum !== expected) {
    console.error(`${impl}: area total ${sum} does not reconcile with Source LOC ${expected}`)
    process.exit(1)
  }
})

for (const area of AREAS) {
  const cells = areaTotals.map((totals) => {
    const value = totals.get(area)!
    return value === 0 ? '—' : value.toLocaleString('en-US')
  })
  if (cells.every((cell) => cell === '—')) continue
  areaRows.push(`| ${area} | ${cells.join(' | ')} |`)
}

const areaTable = areaRows.join('\n')

if (process.argv.includes('--write')) {
  const readmePath = join(repoRoot, 'README.md')
  const readme = readFileSync(readmePath, 'utf8')
  const begin = '<!-- measure:begin'
  const end = '<!-- measure:end -->'
  const beginIndex = readme.indexOf(begin)
  const endIndex = readme.indexOf(end)
  if (beginIndex === -1 || endIndex === -1) {
    console.error('README.md is missing the measure:begin / measure:end markers')
    process.exit(1)
  }
  const beginLineEnd = readme.indexOf('\n', beginIndex)
  let updated = readme.slice(0, beginLineEnd + 1) + table + '\n' + readme.slice(endIndex)

  const areaBegin = updated.indexOf('<!-- areas:begin')
  const areaEnd = updated.indexOf('<!-- areas:end -->')
  if (areaBegin === -1 || areaEnd === -1) {
    console.error('README.md is missing the areas:begin / areas:end markers')
    process.exit(1)
  }
  const areaBeginLineEnd = updated.indexOf('\n', areaBegin)
  updated =
    updated.slice(0, areaBeginLineEnd + 1) + areaTable + '\n' + updated.slice(areaEnd)

  writeFileSync(readmePath, updated)
  console.error('README.md updated')
}

console.log(table)
if (process.argv.includes('--areas')) {
  console.log()
  console.log(areaTable)
}
